kind: Pod
apiVersion: v1
metadata:
  name: hello-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
    - name: hello-ctr
      image: nginx:1.14.2
      ports:
      - containerPort: 8080
      resources:
        limits:
          memory: 128Mi
          cpu: 0.5
